#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re


# ---- Crappy Termhood Approximation ---- #

def is_content_word(word):
    """
    A baseline function for approximating if a word
    is a content word
    :param word:
    :return: True if word is a content word, False otherwise.
    """
    if word.isalpha():
        if len(word) > 2:
            if word.lower() not in stoplist:
                return True
    return False


# ----  Dates  ---- #
DATE_RE = re.compile('(?P<d1>[A-Za-z,\- ]*)(?P<M>-?[0-9][0-9])(?P<Y>..)(?P<d2>[A-Za-z,\- ]*)')


def normalise_date(value):
    """ Transforms a date in a string of the form millennium#year
    TODO: Before JC
    :param value: A year date
    :return: A string date which is split 'millennium#year'
    """
    match = re.search(DATE_RE, value)
    if match:
        millennium = match.groupdict().get("M")
        years = match.groupdict().get("Y")
        # m1, m2 = (match.groupdict().get("d1"), match.groupdict().get("d2"))
        # value = "%s # %s # %s # %s " % (millennium, years, m1, m2)
        return "%s#%s" % (millennium, years)

# French only atm #TODO: allow other languages
stoplist = [
    u'ai',
    u'aie',
    u'aient',
    u'aies',
    u'ait',
    u'alors',
    u'après',
    u'as',
    u'au',
    u'aucuns',
    u'aura',
    u'aurai',
    u'auraient',
    u'aurais',
    u'aurait',
    u'auras',
    u'aurez',
    u'auriez',
    u'aurions',
    u'aurons',
    u'auront',
    u'aussi',
    u'autre',
    u'aux',
    u'avaient',
    u'avais',
    u'avait',
    u'avant',
    u'avec',
    u'avez',
    u'aviez',
    u'avions',
    u'avoir',
    u'avons',
    u'ayant',
    u'ayez',
    u'ayons',
    u'bon',
    u'bons',
    u'bien',
    u'biens',
    u'c',
    u'car',
    u'ce',
    u'ceci',
    u'cela',
    u'celà',
    u'celà',
    u'ces',
    u'cet',
    u'cette',
    u'ceux',
    u'chaque',
    u'chapitre',
    u'chapitres',
    u'ci',
    u'comme',
    u'comment',
    u'd',
    u'dans',
    u'de',
    u'dedans',
    u'dehors',
    u'depuis',
    u'des',
    u'deux',
    u'devrait',
    u'doit',
    u'donc',
    u'dont',
    u'dos',
    u'droite',
    u'du',
    u'début',
    u'elle',
    u'elles',
    u'en',
    u'encore',
    u'entre',
    u'es',
    u'essai',
    u'est',
    u'estre',
    u'et',
    u'eu',
    u'eue',
    u'eues',
    u'eurent',
    u'eus',
    u'eusse',
    u'eussent',
    u'eusses',
    u'eussiez',
    u'eussions',
    u'eut',
    u'eux',
    u'eûmes',
    u'eût',
    u'eûtes',
    u'faire',
    u'fait',
    u'faites',
    u'fois',
    u'font',
    u'force',
    u'furent',
    u'fus',
    u'fusse',
    u'fussent',
    u'fusses',
    u'fussiez',
    u'fussions',
    u'fut',
    u'fûmes',
    u'fût',
    u'fûtes',
    u'haut',
    u'hors',
    u'ici',
    u'il',
    u'ils',
    u'j',
    u'je',
    u'juste',
    u'l',
    u'la',
    u'le',
    u'les',
    u'leur',
    u'leurs',
    u'lui',
    u'là',
    u'm',
    u'ma',
    u'maintenant',
    u'mais',
    u'me',
    u'mes',
    u'mine',
    u'moi',
    u'moins',
    u'mon',
    u'mot',
    u'même',
    u'n',
    u'nbsp',
    u'ne',
    u'ni',
    u'nommés',
    u'nos',
    u'notre',
    u'nous',
    u'nouveaux',
    u'on',
    u'ont',
    u'ou',
    u'où',
    u'page',
    u'pages',
    u'par',
    u'parce',
    u'parole',
    u'pas',
    u'personnes',
    u'peu',
    u'peut',
    u'pièce',
    u'plus',
    u'plupart',
    u'pour',
    u'pourquoi',
    u'qu',
    u'quand',
    u'que',
    u'quel',
    u'quelle',
    u'quelles',
    u'quels',
    u'qui',
    u's',
    u'sa',
    u'sans',
    u'se',
    u'sera',
    u'serai',
    u'seraient',
    u'serais',
    u'serait',
    u'seras',
    u'serez',
    u'seriez',
    u'serions',
    u'serons',
    u'seront',
    u'ses',
    u'seulement',
    u'si',
    u'sien',
    u'soi',
    u'soient',
    u'sois',
    u'soit',
    u'sommes',
    u'son',
    u'sont',
    u'sous',
    u'soyez',
    u'soyons',
    u'suis',
    u'sujet',
    u'sur',
    u't',
    u'ta',
    u'tandis',
    u'te',
    u'tellement',
    u'tels',
    u'tes',
    u'toi',
    u'ton',
    u'tous',
    u'tout',
    u'toute',
    u'trop',
    u'très',
    u'tu',
    u'un',
    u'une',
    u'valeur',
    u'voie',
    u'voient',
    u'vont',
    u'vos',
    u'vostre',
    u'votre',
    u'vous',
    u'vu',
    u'y',
    u'à',
    u'ça',
    u'étaient',
    u'étais',
    u'était',
    u'étant',
    u'état',
    u'étiez',
    u'étions',
    u'été',
    u'étée',
    u'étées',
    u'étés',
    u'êtes',
    u'être',
]